package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AdvanceSalaryInstallment generated by hbm2java
 */
public class AdvanceSalaryInstallment  implements java.io.Serializable {


     private BigDecimal requestId;
     private String employeeId;
     private BigDecimal installmentAmount;
     private BigDecimal installmentNo;
     private String status;

    public AdvanceSalaryInstallment() {
    }

	
    public AdvanceSalaryInstallment(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public AdvanceSalaryInstallment(BigDecimal requestId, String employeeId, BigDecimal installmentAmount, BigDecimal installmentNo, String status) {
       this.requestId = requestId;
       this.employeeId = employeeId;
       this.installmentAmount = installmentAmount;
       this.installmentNo = installmentNo;
       this.status = status;
    }
   
    public BigDecimal getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public BigDecimal getInstallmentAmount() {
        return this.installmentAmount;
    }
    
    public void setInstallmentAmount(BigDecimal installmentAmount) {
        this.installmentAmount = installmentAmount;
    }
    public BigDecimal getInstallmentNo() {
        return this.installmentNo;
    }
    
    public void setInstallmentNo(BigDecimal installmentNo) {
        this.installmentNo = installmentNo;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


