package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AppraisalQuestionsId generated by hbm2java
 */
public class AppraisalQuestionsId  implements java.io.Serializable {


     private BigDecimal questionCode;
     private BigDecimal categoryCode;

    public AppraisalQuestionsId() {
    }

    public AppraisalQuestionsId(BigDecimal questionCode, BigDecimal categoryCode) {
       this.questionCode = questionCode;
       this.categoryCode = categoryCode;
    }
   
    public BigDecimal getQuestionCode() {
        return this.questionCode;
    }
    
    public void setQuestionCode(BigDecimal questionCode) {
        this.questionCode = questionCode;
    }
    public BigDecimal getCategoryCode() {
        return this.categoryCode;
    }
    
    public void setCategoryCode(BigDecimal categoryCode) {
        this.categoryCode = categoryCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppraisalQuestionsId) ) return false;
		 AppraisalQuestionsId castOther = ( AppraisalQuestionsId ) other; 
         
		 return ( (this.getQuestionCode()==castOther.getQuestionCode()) || ( this.getQuestionCode()!=null && castOther.getQuestionCode()!=null && this.getQuestionCode().equals(castOther.getQuestionCode()) ) )
 && ( (this.getCategoryCode()==castOther.getCategoryCode()) || ( this.getCategoryCode()!=null && castOther.getCategoryCode()!=null && this.getCategoryCode().equals(castOther.getCategoryCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQuestionCode() == null ? 0 : this.getQuestionCode().hashCode() );
         result = 37 * result + ( getCategoryCode() == null ? 0 : this.getCategoryCode().hashCode() );
         return result;
   }   


}


