package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * AppraisalGradeMaster generated by hbm2java
 */
public class AppraisalGrade  implements java.io.Serializable {


     private String gradeName;
     private BigDecimal gradeCode;
     private BigDecimal gradePoint;
     private Serializable creationDate;
     private Serializable modificationDate;
     private BigDecimal createdBy;
     private BigDecimal modifiedBy;
     private String status;

    public AppraisalGrade() {
    }

	
    public AppraisalGrade(String gradeName) {
        this.gradeName = gradeName;
    }
    public AppraisalGrade(String gradeName, BigDecimal gradeCode, BigDecimal gradePoint, Serializable creationDate, Serializable modificationDate, BigDecimal createdBy, BigDecimal modifiedBy, String status) {
       this.gradeName = gradeName;
       this.gradeCode = gradeCode;
       this.gradePoint = gradePoint;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.status = status;
    }
   
    public String getGradeName() {
        return this.gradeName;
    }
    
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }
    public BigDecimal getGradeCode() {
        return this.gradeCode;
    }
    
    public void setGradeCode(BigDecimal gradeCode) {
        this.gradeCode = gradeCode;
    }
    public BigDecimal getGradePoint() {
        return this.gradePoint;
    }
    
    public void setGradePoint(BigDecimal gradePoint) {
        this.gradePoint = gradePoint;
    }
    public Serializable getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Serializable creationDate) {
        this.creationDate = creationDate;
    }
    public Serializable getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Serializable modificationDate) {
        this.modificationDate = modificationDate;
    }
    public BigDecimal getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }
    public BigDecimal getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(BigDecimal modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


