package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * AssetAvailability generated by hbm2java
 */
public class AssetAvailability  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal assetId;
     private String employeeId;
     private Date allocationDate;
     private Date validUpTo;
     private String authorizedEmployeeId;
     private String allocationStatus;

    public AssetAvailability() {
    }

	
    public AssetAvailability(BigDecimal id) {
        this.id = id;
    }
    public AssetAvailability(BigDecimal id, BigDecimal assetId, String employeeId, Date allocationDate, Date validUpTo, String authorizedEmployeeId, String allocationStatus) {
       this.id = id;
       this.assetId = assetId;
       this.employeeId = employeeId;
       this.allocationDate = allocationDate;
       this.validUpTo = validUpTo;
       this.authorizedEmployeeId = authorizedEmployeeId;
       this.allocationStatus = allocationStatus;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(BigDecimal assetId) {
        this.assetId = assetId;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public Date getAllocationDate() {
        return this.allocationDate;
    }
    
    public void setAllocationDate(Date allocationDate) {
        this.allocationDate = allocationDate;
    }
    public Date getValidUpTo() {
        return this.validUpTo;
    }
    
    public void setValidUpTo(Date validUpTo) {
        this.validUpTo = validUpTo;
    }
    public String getAuthorizedEmployeeId() {
        return this.authorizedEmployeeId;
    }
    
    public void setAuthorizedEmployeeId(String authorizedEmployeeId) {
        this.authorizedEmployeeId = authorizedEmployeeId;
    }
    public String getAllocationStatus() {
        return this.allocationStatus;
    }
    
    public void setAllocationStatus(String allocationStatus) {
        this.allocationStatus = allocationStatus;
    }




}


