package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AssetsMaster generated by hbm2java
 */
public class AssetsMaster  implements java.io.Serializable {


     private BigDecimal assetid;
     private String assetname;
     private String status;

    public AssetsMaster() {
    }

	
    public AssetsMaster(BigDecimal assetid) {
        this.assetid = assetid;
    }
    public AssetsMaster(BigDecimal assetid, String assetname, String status) {
       this.assetid = assetid;
       this.assetname = assetname;
       this.status = status;
    }
   
    public BigDecimal getAssetid() {
        return this.assetid;
    }
    
    public void setAssetid(BigDecimal assetid) {
        this.assetid = assetid;
    }
    public String getAssetname() {
        return this.assetname;
    }
    
    public void setAssetname(String assetname) {
        this.assetname = assetname;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


