package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Attendence generated by hbm2java
 */
public class Attendence  implements java.io.Serializable {


     private BigDecimal id;
     private String empCode;
     private BigDecimal regularHrs;
     private BigDecimal overtimeHrs;
     private BigDecimal totalHrs;
     private String empName;
     private Date attendanceDate;

    public Date getAttendanceDate() {
        return attendanceDate;
    }

    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }


    public Attendence() {
    }

	
    public Attendence(BigDecimal id) {
        this.id = id;
    }

    public Attendence(BigDecimal id, String empCode, BigDecimal regularHrs, BigDecimal overtimeHrs, BigDecimal totalHrs, String empName, Date attendanceDate) {
        this.id = id;
        this.empCode = empCode;
        this.regularHrs = regularHrs;
        this.overtimeHrs = overtimeHrs;
        this.totalHrs = totalHrs;
        this.empName = empName;
        this.attendanceDate = attendanceDate;
    }
 
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmpCode() {
        return this.empCode;
    }
    
    public void setEmpCode(String empCode) {
        this.empCode = empCode;
    }
  
    
    public BigDecimal getRegularHrs() {
        return this.regularHrs;
    }
    
    public void setRegularHrs(BigDecimal regularHrs) {
        this.regularHrs = regularHrs;
    }
    public BigDecimal getOvertimeHrs() {
        return this.overtimeHrs;
    }
    
    public void setOvertimeHrs(BigDecimal overtimeHrs) {
        this.overtimeHrs = overtimeHrs;
    }
    public BigDecimal getTotalHrs() {
        return this.totalHrs;
    }
    
    public void setTotalHrs(BigDecimal totalHrs) {
        this.totalHrs = totalHrs;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }




}


