package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import com.pojo.Company;
/**
 * BranchMaster generated by hbm2java
 */
public class BranchMaster  implements java.io.Serializable {


     private BigDecimal branchId;
     private String branchName;
     private String branchCode;
     private String branchAddress;
     private BigDecimal branchStateid;
     private BigDecimal branchCityid;
     private String branchPincode;
     private Date branchCreationdate;
     private BigDecimal branchCreatorid;
     private String branchType;
     private Company company;
     private String currency;
     private BigDecimal modifierId;
     private Date modifiedDate;
     private String branchfax;
     private String branchemail;
     private String contactNumber;
     private BigDecimal branchCountryid;
     private String status;

    public BranchMaster() {
    }

	
    public BranchMaster(BigDecimal branchId) {
        this.branchId = branchId;
    }
    public BranchMaster(BigDecimal branchId, String branchName, String branchCode, String branchAddress, BigDecimal branchStateid, BigDecimal branchCityid, String branchPincode, Date branchCreationdate, BigDecimal branchCreatorid, String branchType, Company companyId, String currency, BigDecimal modifierId, Date modifiedDate, String branchfax, String branchemail, String contactNumber, BigDecimal branchCountryid, String status) {
       this.branchId = branchId;
       this.branchName = branchName;
       this.branchCode = branchCode;
       this.branchAddress = branchAddress;
       this.branchStateid = branchStateid;
       this.branchCityid = branchCityid;
       this.branchPincode = branchPincode;
       this.branchCreationdate = branchCreationdate;
       this.branchCreatorid = branchCreatorid;
       this.branchType = branchType;
       this.company = companyId;
       this.currency = currency;
       this.modifierId = modifierId;
       this.modifiedDate = modifiedDate;
       this.branchfax = branchfax;
       this.branchemail = branchemail;
       this.contactNumber = contactNumber;
       this.branchCountryid = branchCountryid;
       this.status = status;
    }
   
    public BigDecimal getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(BigDecimal branchId) {
        this.branchId = branchId;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    public String getBranchAddress() {
        return this.branchAddress;
    }
    
    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress;
    }
    public BigDecimal getBranchStateid() {
        return this.branchStateid;
    }
    
    public void setBranchStateid(BigDecimal branchStateid) {
        this.branchStateid = branchStateid;
    }
    public BigDecimal getBranchCityid() {
        return this.branchCityid;
    }
    
    public void setBranchCityid(BigDecimal branchCityid) {
        this.branchCityid = branchCityid;
    }
    public String getBranchPincode() {
        return this.branchPincode;
    }
    
    public void setBranchPincode(String branchPincode) {
        this.branchPincode = branchPincode;
    }
    public Date getBranchCreationdate() {
        return this.branchCreationdate;
    }
    
    public void setBranchCreationdate(Date branchCreationdate) {
        this.branchCreationdate = branchCreationdate;
    }
    public BigDecimal getBranchCreatorid() {
        return this.branchCreatorid;
    }
    
    public void setBranchCreatorid(BigDecimal branchCreatorid) {
        this.branchCreatorid = branchCreatorid;
    }
    public String getBranchType() {
        return this.branchType;
    }
    
    public void setBranchType(String branchType) {
        this.branchType = branchType;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company companyId) {
        this.company = companyId;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public BigDecimal getModifierId() {
        return this.modifierId;
    }
    
    public void setModifierId(BigDecimal modifierId) {
        this.modifierId = modifierId;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getBranchfax() {
        return this.branchfax;
    }
    
    public void setBranchfax(String branchfax) {
        this.branchfax = branchfax;
    }
    public String getBranchemail() {
        return this.branchemail;
    }
    
    public void setBranchemail(String branchemail) {
        this.branchemail = branchemail;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public BigDecimal getBranchCountryid() {
        return this.branchCountryid;
    }
    
    public void setBranchCountryid(BigDecimal branchCountryid) {
        this.branchCountryid = branchCountryid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


