package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * CityMaster generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private BigDecimal cityId;
     private State stateMaster;
     private String cityName;
     private Date creationDate;
     private Date modificationDate;
     private String createdBy;
     private String modifiedBy;
     private String status;
     private CountryMaster countryMaster;

    public City() {
    }
	
    public City(BigDecimal cityId) {
        this.cityId = cityId;
    }

    public City(BigDecimal cityId, State stateMaster, String cityName, Date creationDate, Date modificationDate, String createdBy, String modifiedBy, String status) {
       this.cityId = cityId;
       this.stateMaster = stateMaster;
       this.cityName = cityName;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.status = status;
    }

    public CountryMaster getCountryMaster() {
        return countryMaster;
    }

    public void setCountryMaster(CountryMaster countryMaster) {
        this.countryMaster = countryMaster;
    }
   
    public BigDecimal getCityId() {
        return this.cityId;
    }
    
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }
    public State getStateMaster() {
        return this.stateMaster;
    }
    
    public void setStateMaster(State stateMaster) {
        this.stateMaster = stateMaster;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


