package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * CompanyMaster generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private BigDecimal companyCode;
     private String companyName;
     private String contactno;
     private String regaddress;
     private String corptaddress;
     private Date entrydate;
     private Date modifydate;
     private BigDecimal createdby;
     private BigDecimal modifiedby;
     private String status;
     private BigDecimal companyTypeid;
     private BigDecimal countryoriginid;
     private String natureOfBusiness;
     private String day;
     private String leaveWeeklyOff;
     private String holidayWeeklyOff;
     private String fromdate;
     private String todate;
     private String leavecal;
     private BigDecimal grcompanyid;
     private BigDecimal stateid;
     private BigDecimal cityid;
     private BigDecimal ptaxrate;
     private String registeraddrPincode;
     private String corporateaddrPincode;
     private String finstartyear;
     private String finendyear;

    public Company() {
    }

	
    public Company(BigDecimal companyCode) {
        this.companyCode = companyCode;
    }
    public Company(BigDecimal companyCode, String companyName, String contactno, String regaddress, String corptaddress, Date entrydate, Date modifydate, BigDecimal createdby, BigDecimal modifiedby, String status, BigDecimal companyTypeid, BigDecimal countryoriginid, String natureOfBusiness, String day, String leaveWeeklyOff, String holidayWeeklyOff, String fromdate, String todate, String leavecal, BigDecimal grcompanyid, BigDecimal stateid, BigDecimal cityid, BigDecimal ptaxrate, String registeraddrPincode, String corporateaddrPincode, String finstartyear, String finendyear) {
       this.companyCode = companyCode;
       this.companyName = companyName;
       this.contactno = contactno;
       this.regaddress = regaddress;
       this.corptaddress = corptaddress;
       this.entrydate = entrydate;
       this.modifydate = modifydate;
       this.createdby = createdby;
       this.modifiedby = modifiedby;
       this.status = status;
       this.companyTypeid = companyTypeid;
       this.countryoriginid = countryoriginid;
       this.natureOfBusiness = natureOfBusiness;
       this.day = day;
       this.leaveWeeklyOff = leaveWeeklyOff;
       this.holidayWeeklyOff = holidayWeeklyOff;
       this.fromdate = fromdate;
       this.todate = todate;
       this.leavecal = leavecal;
       this.grcompanyid = grcompanyid;
       this.stateid = stateid;
       this.cityid = cityid;
       this.ptaxrate = ptaxrate;
       this.registeraddrPincode = registeraddrPincode;
       this.corporateaddrPincode = corporateaddrPincode;
       this.finstartyear = finstartyear;
       this.finendyear = finendyear;
    }
   
    public BigDecimal getCompanyCode() {
        return this.companyCode;
    }
    
    public void setCompanyCode(BigDecimal companyCode) {
        this.companyCode = companyCode;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getContactno() {
        return contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    
    public String getRegaddress() {
        return this.regaddress;
    }
    
    public void setRegaddress(String regaddress) {
        this.regaddress = regaddress;
    }
    public String getCorptaddress() {
        return this.corptaddress;
    }
    
    public void setCorptaddress(String corptaddress) {
        this.corptaddress = corptaddress;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }
    
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
    public BigDecimal getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(BigDecimal createdby) {
        this.createdby = createdby;
    }
    public BigDecimal getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(BigDecimal modifiedby) {
        this.modifiedby = modifiedby;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getCompanyTypeid() {
        return this.companyTypeid;
    }
    
    public void setCompanyTypeid(BigDecimal companyTypeid) {
        this.companyTypeid = companyTypeid;
    }
    public BigDecimal getCountryoriginid() {
        return this.countryoriginid;
    }
    
    public void setCountryoriginid(BigDecimal countryoriginid) {
        this.countryoriginid = countryoriginid;
    }
    public String getNatureOfBusiness() {
        return this.natureOfBusiness;
    }
    
    public void setNatureOfBusiness(String natureOfBusiness) {
        this.natureOfBusiness = natureOfBusiness;
    }
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    public String getLeaveWeeklyOff() {
        return this.leaveWeeklyOff;
    }
    
    public void setLeaveWeeklyOff(String leaveWeeklyOff) {
        this.leaveWeeklyOff = leaveWeeklyOff;
    }
    public String getHolidayWeeklyOff() {
        return this.holidayWeeklyOff;
    }
    
    public void setHolidayWeeklyOff(String holidayWeeklyOff) {
        this.holidayWeeklyOff = holidayWeeklyOff;
    }
    public String getFromdate() {
        return this.fromdate;
    }
    
    public void setFromdate(String fromdate) {
        this.fromdate = fromdate;
    }
    public String getTodate() {
        return this.todate;
    }
    
    public void setTodate(String todate) {
        this.todate = todate;
    }
    public String getLeavecal() {
        return this.leavecal;
    }
    
    public void setLeavecal(String leavecal) {
        this.leavecal = leavecal;
    }
    public BigDecimal getGrcompanyid() {
        return this.grcompanyid;
    }
    
    public void setGrcompanyid(BigDecimal grcompanyid) {
        this.grcompanyid = grcompanyid;
    }
    public BigDecimal getStateid() {
        return this.stateid;
    }
    
    public void setStateid(BigDecimal stateid) {
        this.stateid = stateid;
    }
    public BigDecimal getCityid() {
        return this.cityid;
    }
    
    public void setCityid(BigDecimal cityid) {
        this.cityid = cityid;
    }
    public BigDecimal getPtaxrate() {
        return this.ptaxrate;
    }
    
    public void setPtaxrate(BigDecimal ptaxrate) {
        this.ptaxrate = ptaxrate;
    }
    public String getRegisteraddrPincode() {
        return this.registeraddrPincode;
    }
    
    public void setRegisteraddrPincode(String registeraddrPincode) {
        this.registeraddrPincode = registeraddrPincode;
    }
    public String getCorporateaddrPincode() {
        return this.corporateaddrPincode;
    }
    
    public void setCorporateaddrPincode(String corporateaddrPincode) {
        this.corporateaddrPincode = corporateaddrPincode;
    }
    public String getFinstartyear() {
        return this.finstartyear;
    }
    
    public void setFinstartyear(String finstartyear) {
        this.finstartyear = finstartyear;
    }
    public String getFinendyear() {
        return this.finendyear;
    }
    
    public void setFinendyear(String finendyear) {
        this.finendyear = finendyear;
    }




}


