package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * CompanyTypeMaster generated by hbm2java
 */
public class CompanyTypeMaster  implements java.io.Serializable {


     private BigDecimal compTypeId;
     private String compTypeName;

    public CompanyTypeMaster() {
    }

    public CompanyTypeMaster(BigDecimal compTypeId, String compTypeName) {
       this.compTypeId = compTypeId;
       this.compTypeName = compTypeName;
    }
   
    public BigDecimal getCompTypeId() {
        return this.compTypeId;
    }
    
    public void setCompTypeId(BigDecimal compTypeId) {
        this.compTypeId = compTypeId;
    }
    public String getCompTypeName() {
        return this.compTypeName;
    }
    
    public void setCompTypeName(String compTypeName) {
        this.compTypeName = compTypeName;
    }




}


