package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.sql.Timestamp;
/**
 * ConferenceRoomBooking generated by hbm2java
 */
public class ConferenceRoomBooking  implements java.io.Serializable {

     private BigDecimal conferenceroombookingcode;
     private String employeeid;

     private String roomno;
  
     private Timestamp fromtime;
     private Timestamp totime;
     private String reason;
     private String status;
     private String approvalauthorityEmployeeid;
     private Date requestdate;
     private Date approvaldate;

    public ConferenceRoomBooking() {
    }

    public ConferenceRoomBooking(BigDecimal conferenceroombookingcode, String employeeid, String roomno, Timestamp fromtime, Timestamp totime, String reason, String status, String approvalauthorityEmployeeid, Date requestdate, Date approvaldate) {
        this.conferenceroombookingcode = conferenceroombookingcode;
        this.employeeid = employeeid;
        this.roomno = roomno;
        this.fromtime = fromtime;
        this.totime = totime;
        this.reason = reason;
        this.status = status;
        this.approvalauthorityEmployeeid = approvalauthorityEmployeeid;
        this.requestdate = requestdate;
        this.approvaldate = approvaldate;
    }

    public String getApprovalauthorityEmployeeid() {
        return approvalauthorityEmployeeid;
    }

    public void setApprovalauthorityEmployeeid(String approvalauthorityEmployeeid) {
        this.approvalauthorityEmployeeid = approvalauthorityEmployeeid;
    }

    public Date getApprovaldate() {
        return approvaldate;
    }

    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }

    public BigDecimal getConferenceroombookingcode() {
        return conferenceroombookingcode;
    }

    public void setConferenceroombookingcode(BigDecimal conferenceroombookingcode) {
        this.conferenceroombookingcode = conferenceroombookingcode;
    }

    public String getEmployeeid() {
        return employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    public Timestamp getFromtime() {
        return fromtime;
    }

    public void setFromtime(Timestamp fromtime) {
        this.fromtime = fromtime;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Date getRequestdate() {
        return requestdate;
    }

    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }

    public String getRoomno() {
        return roomno;
    }

    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getTotime() {
        return totime;
    }

    public void setTotime(Timestamp totime) {
        this.totime = totime;
    }


}


