package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ConferenceRoomMaster generated by hbm2java
 */
public class ConferenceRoomMaster  implements java.io.Serializable {


     private BigDecimal id;
     private String roomstatus;
     private BigDecimal strength;
     private String roomdeatils;
     private String buildingname;
     private BigDecimal floorno;
     private BigDecimal roomno;

    public ConferenceRoomMaster() {
    }

	
    public ConferenceRoomMaster(BigDecimal id) {
        this.id = id;
    }
    public ConferenceRoomMaster(BigDecimal id, String roomstatus, BigDecimal strength, String roomdeatils, String buildingname, BigDecimal floorno, BigDecimal roomno) {
       this.id = id;
       this.roomstatus = roomstatus;
       this.strength = strength;
       this.roomdeatils = roomdeatils;
       this.buildingname = buildingname;
       this.floorno = floorno;
       this.roomno = roomno;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getRoomstatus() {
        return this.roomstatus;
    }
    
    public void setRoomstatus(String roomstatus) {
        this.roomstatus = roomstatus;
    }
    public BigDecimal getStrength() {
        return this.strength;
    }
    
    public void setStrength(BigDecimal strength) {
        this.strength = strength;
    }
    public String getRoomdeatils() {
        return this.roomdeatils;
    }
    
    public void setRoomdeatils(String roomdeatils) {
        this.roomdeatils = roomdeatils;
    }
    public String getBuildingname() {
        return this.buildingname;
    }
    
    public void setBuildingname(String buildingname) {
        this.buildingname = buildingname;
    }
    public BigDecimal getFloorno() {
        return this.floorno;
    }
    
    public void setFloorno(BigDecimal floorno) {
        this.floorno = floorno;
    }
    public BigDecimal getRoomno() {
        return this.roomno;
    }
    
    public void setRoomno(BigDecimal roomno) {
        this.roomno = roomno;
    }




}


