package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ConsultantMaster generated by hbm2java
 */
public class ConsultantMaster  implements java.io.Serializable {


     private BigDecimal consultancyId;
     private String consultancyName;
     private BigDecimal skillId;
     private String status;

    public ConsultantMaster() {
    }

	
    public ConsultantMaster(BigDecimal consultancyId) {
        this.consultancyId = consultancyId;
    }
    public ConsultantMaster(BigDecimal consultancyId, String consultancyName, BigDecimal skillId, String status) {
       this.consultancyId = consultancyId;
       this.consultancyName = consultancyName;
       this.skillId = skillId;
       this.status = status;
    }
   
    public BigDecimal getConsultancyId() {
        return this.consultancyId;
    }
    
    public void setConsultancyId(BigDecimal consultancyId) {
        this.consultancyId = consultancyId;
    }
    public String getConsultancyName() {
        return this.consultancyName;
    }
    
    public void setConsultancyName(String consultancyName) {
        this.consultancyName = consultancyName;
    }
    public BigDecimal getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(BigDecimal skillId) {
        this.skillId = skillId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


