package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CountryMaster generated by hbm2java
 */
public class CountryMaster  implements java.io.Serializable {


     private BigDecimal countryId;
     private String countryName;
     private String currencyName;
     private Date creationDate;
     private Date modificationDate;
     private String createdBy;
     private String modifiedBy;
     private String status;
     private String currencyAbbreviation;
     private Set<State> stateMasters = new HashSet<State>(0);
     
     
    public CountryMaster() {
    }

    
    public CountryMaster(BigDecimal countryId) {
        this.countryId = countryId;
    }
    public CountryMaster(BigDecimal countryId, String countryName, String currencyName, Date creationDate, Date modificationDate, String createdBy, String modifiedBy, String status, String currencyAbbreviation, Set<State> stateMasters) {
       this.countryId = countryId;
       this.countryName = countryName;
       this.currencyName = currencyName;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.status = status;
       this.currencyAbbreviation = currencyAbbreviation;
       this.stateMasters = stateMasters;
    }
   
    public BigDecimal getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(BigDecimal countryId) {
        this.countryId = countryId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public String getCurrencyName() {
        return this.currencyName;
    }
    
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCurrencyAbbreviation() {
        return this.currencyAbbreviation;
    }
    
    public void setCurrencyAbbreviation(String currencyAbbreviation) {
        this.currencyAbbreviation = currencyAbbreviation;
    }
    public Set<State> getStateMasters() {
        return this.stateMasters;
    }
    
    public void setStateMasters(Set<State> stateMasters) {
        this.stateMasters = stateMasters;
    }




}


