package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * EmployeeConfirmation generated by hbm2java
 */
public class EmployeeConfirmation  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private Date confDate;
     private Character status;
     private Date confDueDate;
     private Date effectiveFrom;

    public EmployeeConfirmation() {
    }

	
    public EmployeeConfirmation(BigDecimal id) {
        this.id = id;
    }
    public EmployeeConfirmation(BigDecimal id, String employeeId, Date confDate, Character status, Date confDueDate, Date effectiveFrom) {
       this.id = id;
       this.employeeId = employeeId;
       this.confDate = confDate;
       this.status = status;
       this.confDueDate = confDueDate;
       this.effectiveFrom = effectiveFrom;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public Date getConfDate() {
        return this.confDate;
    }
    
    public void setConfDate(Date confDate) {
        this.confDate = confDate;
    }
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    public Date getConfDueDate() {
        return this.confDueDate;
    }
    
    public void setConfDueDate(Date confDueDate) {
        this.confDueDate = confDueDate;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }




}


