package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * EmployeeFamilyDetails generated by hbm2java
 */
public class EmployeeFamilyDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private String familyMemberName;
     private String relation;
     private Date dobOfMember;

    public EmployeeFamilyDetails() {
    }

	
    public EmployeeFamilyDetails(BigDecimal id) {
        this.id = id;
    }
    public EmployeeFamilyDetails(BigDecimal id, String employeeId, String familyMemberName, String relation, Date dobOfMember) {
       this.id = id;
       this.employeeId = employeeId;
       this.familyMemberName = familyMemberName;
       this.relation = relation;
       this.dobOfMember = dobOfMember;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getFamilyMemberName() {
        return this.familyMemberName;
    }
    
    public void setFamilyMemberName(String familyMemberName) {
        this.familyMemberName = familyMemberName;
    }
    public String getRelation() {
        return this.relation;
    }
    
    public void setRelation(String relation) {
        this.relation = relation;
    }
    public Date getDobOfMember() {
        return this.dobOfMember;
    }
    
    public void setDobOfMember(Date dobOfMember) {
        this.dobOfMember = dobOfMember;
    }




}


