package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * EmployeeEducationDetails generated by hbm2java
 */
public class EmployeeEducationDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private String examinationName;
     private Date yearOfStart;
     private Date yearOfEnd;
     private BigDecimal percentage;
     private String boardName;
     private String institutionName;
     private String specialisation;

    public EmployeeEducationDetails() {
    }

	
    public EmployeeEducationDetails(BigDecimal id) {
        this.id = id;
    }
    public EmployeeEducationDetails(BigDecimal id, String employeeId, String examinationName, Date yearOfStart, Date yearOfEnd, BigDecimal percentage, String boardName, String institutionName, String specialisation) {
       this.id = id;
       this.employeeId = employeeId;
       this.examinationName = examinationName;
       this.yearOfStart = yearOfStart;
       this.yearOfEnd = yearOfEnd;
       this.percentage = percentage;
       this.boardName = boardName;
       this.institutionName = institutionName;
       this.specialisation = specialisation;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getExaminationName() {
        return this.examinationName;
    }
    
    public void setExaminationName(String examinationName) {
        this.examinationName = examinationName;
    }
    public Date getYearOfStart() {
        return this.yearOfStart;
    }
    
    public void setYearOfStart(Date yearOfStart) {
        this.yearOfStart = yearOfStart;
    }
    public Date getYearOfEnd() {
        return this.yearOfEnd;
    }
    
    public void setYearOfEnd(Date yearOfEnd) {
        this.yearOfEnd = yearOfEnd;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public String getBoardName() {
        return this.boardName;
    }
    
    public void setBoardName(String boardName) {
        this.boardName = boardName;
    }
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }
    public String getSpecialisation() {
        return this.specialisation;
    }
    
    public void setSpecialisation(String specialisation) {
        this.specialisation = specialisation;
    }




}


