package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA

//Created by Pradipto
import java.math.BigDecimal;
import java.util.Date;

/**
 * EmployeeSkill generated by hbm2java
 */
public class EmployeeSkill  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private Skills skillId;
     private String proficiencyLevel;
     private Date lastUsed;

    public Skills getSkillId() {
        return skillId;
    }

    public void setSkillId(Skills skillId) {
        this.skillId = skillId;
    }

    public EmployeeSkill() {
    }

	
    public EmployeeSkill(BigDecimal id) {
        this.id = id;
    }
    
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    public String getProficiencyLevel() {
        return this.proficiencyLevel;
    }
    
    public void setProficiencyLevel(String proficiencyLevel) {
        this.proficiencyLevel = proficiencyLevel;
    }
    public Date getLastUsed() {
        return this.lastUsed;
    }
    
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }




}


