package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * FacilityRequisition generated by hbm2java
 */
public class FacilityRequisition  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeid;
     private String facilityname;
     private String reason;
     private String status;
     private String tomail;
     private String approvalauthoriyEmployeeid;
     private Date requestdate;
     private Date approvaldate;

    public FacilityRequisition() {
    }

	
    public FacilityRequisition(BigDecimal id) {
        this.id = id;
    }
    public FacilityRequisition(BigDecimal id, String employeeid, String facilityname, String reason, String status, String tomail, String approvalauthoriyEmployeeid, Date requestdate, Date approvaldate) {
       this.id = id;
       this.employeeid = employeeid;
       this.facilityname = facilityname;
       this.reason = reason;
       this.status = status;
       this.tomail = tomail;
       this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
       this.requestdate = requestdate;
       this.approvaldate = approvaldate;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    public String getFacilityname() {
        return this.facilityname;
    }
    
    public void setFacilityname(String facilityname) {
        this.facilityname = facilityname;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTomail() {
        return this.tomail;
    }
    
    public void setTomail(String tomail) {
        this.tomail = tomail;
    }
    public String getApprovalauthoriyEmployeeid() {
        return this.approvalauthoriyEmployeeid;
    }
    
    public void setApprovalauthoriyEmployeeid(String approvalauthoriyEmployeeid) {
        this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
    }
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }




}


