package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * GroupCompanyMaster generated by hbm2java
 */
public class GroupCompanyMaster  implements java.io.Serializable {


     private BigDecimal companygrId;
     private String companyGroupName;
     private String corporateAddress;
     private String pincode;
     private String location;
     private BigDecimal creatorId;
     private Date creationDate;
     private BigDecimal modifierId;
     private Date modifiedDate;
     private String status;

    public GroupCompanyMaster() {
    }

	
    public GroupCompanyMaster(BigDecimal companygrId, String companyGroupName) {
        this.companygrId = companygrId;
        this.companyGroupName = companyGroupName;
    }
    public GroupCompanyMaster(BigDecimal companygrId, String companyGroupName, String corporateAddress, String pincode, String location, BigDecimal creatorId, Date creationDate, BigDecimal modifierId, Date modifiedDate, String status) {
       this.companygrId = companygrId;
       this.companyGroupName = companyGroupName;
       this.corporateAddress = corporateAddress;
       this.pincode = pincode;
       this.location = location;
       this.creatorId = creatorId;
       this.creationDate = creationDate;
       this.modifierId = modifierId;
       this.modifiedDate = modifiedDate;
       this.status = status;
    }
   
    public BigDecimal getCompanygrId() {
        return this.companygrId;
    }
    
    public void setCompanygrId(BigDecimal companygrId) {
        this.companygrId = companygrId;
    }
    public String getCompanyGroupName() {
        return this.companyGroupName;
    }
    
    public void setCompanyGroupName(String companyGroupName) {
        this.companyGroupName = companyGroupName;
    }
    public String getCorporateAddress() {
        return this.corporateAddress;
    }
    
    public void setCorporateAddress(String corporateAddress) {
        this.corporateAddress = corporateAddress;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public BigDecimal getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(BigDecimal creatorId) {
        this.creatorId = creatorId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public BigDecimal getModifierId() {
        return this.modifierId;
    }
    
    public void setModifierId(BigDecimal modifierId) {
        this.modifierId = modifierId;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


