package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * LeaveMaster generated by hbm2java
 */
public class LeaveDetails  implements java.io.Serializable {


     private BigDecimal leaveid;
     private String leavetype;
     private String carryfwenabled;
     private String encashmentenabled;
     private String leavestatus;
     private String companyname;
     private String entitledfor;

    public LeaveDetails() {
    }

	
    public LeaveDetails(BigDecimal leaveid) {
        this.leaveid = leaveid;
    }
    public LeaveDetails(BigDecimal leaveid, String leavetype, String carryfwenabled, String encashmentenabled, String leavestatus, String companyname, String entitledfor) {
       this.leaveid = leaveid;
       this.leavetype = leavetype;
       this.carryfwenabled = carryfwenabled;
       this.encashmentenabled = encashmentenabled;
       this.leavestatus = leavestatus;
       this.companyname = companyname;
       this.entitledfor = entitledfor;
    }
   
    public BigDecimal getLeaveid() {
        return this.leaveid;
    }
    
    public void setLeaveid(BigDecimal leaveid) {
        this.leaveid = leaveid;
    }
    public String getLeavetype() {
        return this.leavetype;
    }
    
    public void setLeavetype(String leavetype) {
        this.leavetype = leavetype;
    }
    public String getCarryfwenabled() {
        return this.carryfwenabled;
    }
    
    public void setCarryfwenabled(String carryfwenabled) {
        this.carryfwenabled = carryfwenabled;
    }
    public String getEncashmentenabled() {
        return this.encashmentenabled;
    }
    
    public void setEncashmentenabled(String encashmentenabled) {
        this.encashmentenabled = encashmentenabled;
    }
    public String getLeavestatus() {
        return this.leavestatus;
    }
    
    public void setLeavestatus(String leavestatus) {
        this.leavestatus = leavestatus;
    }
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getEntitledfor() {
        return this.entitledfor;
    }
    
    public void setEntitledfor(String entitledfor) {
        this.entitledfor = entitledfor;
    }




}


