package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LeaveApply generated by hbm2java
 */
public class Leave  implements java.io.Serializable {


     private BigDecimal requestid;
     private String empid;
     private Double day;
     private Date fromDate;
     private Date toDate;
     private String reason;
     private String leaveAddress;
     private String leaveContactno;
     private String leavestatus;
     private Double noofdays;
     private Integer leaveType;
     private String email;
     private String approvalauthoriyEmployeeid;
     private Date requestdate;
     private Date approvaldate;
     private String whyreject;

    public Leave() {
    }

	
    public Leave(BigDecimal requestid) {
        this.requestid = requestid;
    }
    public Leave(BigDecimal requestid, String empid,Double day, Date fromDate, Date toDate, String reason, String leaveAddress, String leaveContactno, String leavestatus, Double noofdays,Integer leaveType, String email, String approvalauthoriyEmployeeid, Date requestdate, Date approvaldate, String whyreject) {
       this.requestid = requestid;
       this.empid = empid;
       this.day = day;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.reason = reason;
       this.leaveAddress = leaveAddress;
       this.leaveContactno = leaveContactno;
       this.leavestatus = leavestatus;
       this.noofdays = noofdays;
       this.leaveType = leaveType;
       this.email = email;
       this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
       this.requestdate = requestdate;
       this.approvaldate = approvaldate;
       this.whyreject = whyreject;
    }
   
    public BigDecimal getRequestid() {
        return this.requestid;
    }
    
    public void setRequestid(BigDecimal requestid) {
        this.requestid = requestid;
    }
    public String getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(String empid) {
        this.empid = empid;
    }
    
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getLeaveAddress() {
        return this.leaveAddress;
    }
    
    public void setLeaveAddress(String leaveAddress) {
        this.leaveAddress = leaveAddress;
    }
    public String getLeaveContactno() {
        return this.leaveContactno;
    }
    
    public void setLeaveContactno(String leaveContactno) {
        this.leaveContactno = leaveContactno;
    }
    public String getLeavestatus() {
        return this.leavestatus;
    }
    
    public void setLeavestatus(String leavestatus) {
        this.leavestatus = leavestatus;
    }
    public Double getNoofdays() {
        return this.noofdays;
    }

    public Double getDay() {
        return day;
    }

    public void setDay(Double day) {
        this.day = day;
    }

  

    public Integer getLeaveType() {
        return leaveType;
    }

    public void setLeaveType(Integer leaveType) {
        this.leaveType = leaveType;
    }


    public void setNoofdays(Double noofdays) {
        this.noofdays = noofdays;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getApprovalauthoriyEmployeeid() {
        return this.approvalauthoriyEmployeeid;
    }
    
    public void setApprovalauthoriyEmployeeid(String approvalauthoriyEmployeeid) {
        this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
    }
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }
    public String getWhyreject() {
        return this.whyreject;
    }
    
    public void setWhyreject(String whyreject) {
        this.whyreject = whyreject;
    }




}


