package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private BigDecimal requestid;
     private String employeeid;
     private Double totalsalary;
     private Double loanamount;
     private BigDecimal noofinstallment;
     private Date deductionstartmonth;
     private String approvalstatus;
     private String reason;
     private String approvalauthoriyEmployeeid;
     private Date approvaldate;
     private Date requestdate;

    public Loan() {
    }

	
    public Loan(BigDecimal requestid) {
        this.requestid = requestid;
    }
    public Loan(BigDecimal requestid, String employeeid, Double totalsalary, Double loanamount, BigDecimal noofinstallment, Date deductionstartmonth, String approvalstatus, String reason, String approvalauthoriyEmployeeid, Date approvaldate, Date requestdate) {
       this.requestid = requestid;
       this.employeeid = employeeid;
       this.totalsalary = totalsalary;
       this.loanamount = loanamount;
       this.noofinstallment = noofinstallment;
       this.deductionstartmonth = deductionstartmonth;
       this.approvalstatus = approvalstatus;
       this.reason = reason;
       this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
       this.approvaldate = approvaldate;
       this.requestdate = requestdate;
    }
   
    public BigDecimal getRequestid() {
        return this.requestid;
    }
    
    public void setRequestid(BigDecimal requestid) {
        this.requestid = requestid;
    }
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    public Double getTotalsalary() {
        return this.totalsalary;
    }
    
    public void setTotalsalary(Double totalsalary) {
        this.totalsalary = totalsalary;
    }
    public Double getLoanamount() {
        return this.loanamount;
    }
    
    public void setLoanamount(Double loanamount) {
        this.loanamount = loanamount;
    }
    public BigDecimal getNoofinstallment() {
        return this.noofinstallment;
    }
    
    public void setNoofinstallment(BigDecimal noofinstallment) {
        this.noofinstallment = noofinstallment;
    }
    public Date getDeductionstartmonth() {
        return this.deductionstartmonth;
    }
    
    public void setDeductionstartmonth(Date deductionstartmonth) {
        this.deductionstartmonth = deductionstartmonth;
    }
    public String getApprovalstatus() {
        return this.approvalstatus;
    }
    
    public void setApprovalstatus(String approvalstatus) {
        this.approvalstatus = approvalstatus;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getApprovalauthoriyEmployeeid() {
        return this.approvalauthoriyEmployeeid;
    }
    
    public void setApprovalauthoriyEmployeeid(String approvalauthoriyEmployeeid) {
        this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }




}


