package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String userId;
     private String password;
     private Serializable lastLogin;
     private String role;
     private String roleName;

    public Login() {
    }

	
    public Login(String userId) {
        this.userId = userId;
    }
    public Login(String userId, String password, Serializable lastLogin, String role, String roleName) {
       this.userId = userId;
       this.password = password;
       this.lastLogin = lastLogin;
       this.role = role;
       this.roleName = roleName;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Serializable getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Serializable lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }




}


