package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Manualattendence generated by hbm2java
 */
public class Manualattendence  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal totalworkingDay;
     private BigDecimal absentDay;
     private Date entrydate;
     private BigDecimal modifyby;
     private BigDecimal createdby;
     private Date modifydate;
     private String employeeId;
     private BigDecimal companyid;
     private String day;
     private String month;
     private String year;

    public Manualattendence() {
    }

	
    public Manualattendence(BigDecimal id) {
        this.id = id;
    }
    public Manualattendence(BigDecimal id, BigDecimal totalworkingDay, BigDecimal absentDay, Date entrydate, BigDecimal modifyby, BigDecimal createdby, Date modifydate, String employeeId, BigDecimal companyid, String day, String month, String year) {
       this.id = id;
       this.totalworkingDay = totalworkingDay;
       this.absentDay = absentDay;
       this.entrydate = entrydate;
       this.modifyby = modifyby;
       this.createdby = createdby;
       this.modifydate = modifydate;
       this.employeeId = employeeId;
       this.companyid = companyid;
       this.day = day;
       this.month = month;
       this.year = year;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getTotalworkingDay() {
        return this.totalworkingDay;
    }
    
    public void setTotalworkingDay(BigDecimal totalworkingDay) {
        this.totalworkingDay = totalworkingDay;
    }
    public BigDecimal getAbsentDay() {
        return this.absentDay;
    }
    
    public void setAbsentDay(BigDecimal absentDay) {
        this.absentDay = absentDay;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public BigDecimal getModifyby() {
        return this.modifyby;
    }
    
    public void setModifyby(BigDecimal modifyby) {
        this.modifyby = modifyby;
    }
    public BigDecimal getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(BigDecimal createdby) {
        this.createdby = createdby;
    }
    public Date getModifydate() {
        return this.modifydate;
    }
    
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public BigDecimal getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }




}


