package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private BigDecimal pageId;
     private BigDecimal privilegeId;
     private BigDecimal parentPageId;
     private String pageLink;
     private String menuText;
     private String module;

    public String getModule() {
        return module;
    }

    public void setModule(String mod) {
        this.module = mod;
    }
     

    public Menu() {
    }

	
    public Menu(BigDecimal pageId) {
        this.pageId = pageId;
    }
    public Menu(BigDecimal pageId, BigDecimal privilegeId, BigDecimal parentPageId, String pageLink, String menuText) {
       this.pageId = pageId;
       this.privilegeId = privilegeId;
       this.parentPageId = parentPageId;
       this.pageLink = pageLink;
       this.menuText = menuText;
    }
   
    public BigDecimal getPageId() {
        return this.pageId;
    }
    
    public void setPageId(BigDecimal pageId) {
        this.pageId = pageId;
    }
    public BigDecimal getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(BigDecimal privilegeId) {
        this.privilegeId = privilegeId;
    }
    public BigDecimal getParentPageId() {
        return this.parentPageId;
    }
    
    public void setParentPageId(BigDecimal parentPageId) {
        this.parentPageId = parentPageId;
    }
    public String getPageLink() {
        return this.pageLink;
    }
    
    public void setPageLink(String pageLink) {
        this.pageLink = pageLink;
    }
    public String getMenuText() {
        return this.menuText;
    }
    
    public void setMenuText(String menuText) {
        this.menuText = menuText;
    }




}


