package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PassengerDetails generated by hbm2java
 */
public class PassengerDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeid;
     private String memberName;
     private String memberRelation;
     private Date memberDob;
     private Integer familyid;

    public Integer getFamilyid() {
        return familyid;
    }

    public void setFamilyid(Integer familyid) {
        this.familyid = familyid;
    }
     

    public PassengerDetails() {
    }

	
    public PassengerDetails(BigDecimal id) {
        this.id = id;
    }
    public PassengerDetails(BigDecimal id, String employeeid, String memberName, String memberRelation, Date memberDob) {
       this.id = id;
       this.employeeid = employeeid;
       this.memberName = memberName;
       this.memberRelation = memberRelation;
       this.memberDob = memberDob;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    public String getMemberName() {
        return this.memberName;
    }
    
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }
    public String getMemberRelation() {
        return this.memberRelation;
    }
    
    public void setMemberRelation(String memberRelation) {
        this.memberRelation = memberRelation;
    }
    public Date getMemberDob() {
        return this.memberDob;
    }
    
    public void setMemberDob(Date memberDob) {
        this.memberDob = memberDob;
    }




}


