package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PercentageMasteer generated by hbm2java
 */
public class PercentageMasteer  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal roleId;
     private Double loanPer;
     private Double advancedsalaryPer;

    public PercentageMasteer() {
    }

	
    public PercentageMasteer(BigDecimal id) {
        this.id = id;
    }
    public PercentageMasteer(BigDecimal id, BigDecimal roleId, Double loanPer, Double advancedsalaryPer) {
       this.id = id;
       this.roleId = roleId;
       this.loanPer = loanPer;
       this.advancedsalaryPer = advancedsalaryPer;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public Double getLoanPer() {
        return this.loanPer;
    }
    
    public void setLoanPer(Double loanPer) {
        this.loanPer = loanPer;
    }
    public Double getAdvancedsalaryPer() {
        return this.advancedsalaryPer;
    }
    
    public void setAdvancedsalaryPer(Double advancedsalaryPer) {
        this.advancedsalaryPer = advancedsalaryPer;
    }




}


