package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PreviousEmployerDetails generated by hbm2java
 */
public class PreviousEmployerDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private String employerName;
     private String jobDescription;
     private Date joiningDate;
     private Date releaseDate;

    public PreviousEmployerDetails() {
    }

	
    public PreviousEmployerDetails(BigDecimal id) {
        this.id = id;
    }
    public PreviousEmployerDetails(BigDecimal id, String employeeId, String employerName, String jobDescription, Date joiningDate, Date releaseDate) {
       this.id = id;
       this.employeeId = employeeId;
       this.employerName = employerName;
       this.jobDescription = jobDescription;
       this.joiningDate = joiningDate;
       this.releaseDate = releaseDate;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getEmployerName() {
        return this.employerName;
    }
    
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }
    public String getJobDescription() {
        return this.jobDescription;
    }
    
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }
    public Date getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }




}


