package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PrivilegeMaster generated by hbm2java
 */
public class PrivilegeMaster  implements java.io.Serializable {


     private BigDecimal priviledgeId;
     private String priviledgeName;
     private BigDecimal roleId;
     private BigDecimal alocatedBy;

    public PrivilegeMaster() {
    }

	
    public PrivilegeMaster(BigDecimal priviledgeId) {
        this.priviledgeId = priviledgeId;
    }
    public PrivilegeMaster(BigDecimal priviledgeId, String priviledgeName, BigDecimal roleId, BigDecimal alocatedBy) {
       this.priviledgeId = priviledgeId;
       this.priviledgeName = priviledgeName;
       this.roleId = roleId;
       this.alocatedBy = alocatedBy;
    }
   
    public BigDecimal getPriviledgeId() {
        return this.priviledgeId;
    }
    
    public void setPriviledgeId(BigDecimal priviledgeId) {
        this.priviledgeId = priviledgeId;
    }
    public String getPriviledgeName() {
        return this.priviledgeName;
    }
    
    public void setPriviledgeName(String priviledgeName) {
        this.priviledgeName = priviledgeName;
    }
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public BigDecimal getAlocatedBy() {
        return this.alocatedBy;
    }
    
    public void setAlocatedBy(BigDecimal alocatedBy) {
        this.alocatedBy = alocatedBy;
    }




}


