package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProfReferenceDetails generated by hbm2java
 */
public class ProfReferenceDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeId;
     private String referenceName;
     private String referralOrganizationName;
     private String refContactNo;
     private String refEmailAddress;
     private String refDesignation;
     private String refRelaltion;

    public ProfReferenceDetails() {
    }

	
    public ProfReferenceDetails(BigDecimal id) {
        this.id = id;
    }
    public ProfReferenceDetails(BigDecimal id, String employeeId, String referenceName, String referralOrganizationName, String refContactNo, String refEmailAddress, String refDesignation, String refRelaltion) {
       this.id = id;
       this.employeeId = employeeId;
       this.referenceName = referenceName;
       this.referralOrganizationName = referralOrganizationName;
       this.refContactNo = refContactNo;
       this.refEmailAddress = refEmailAddress;
       this.refDesignation = refDesignation;
       this.refRelaltion = refRelaltion;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getReferenceName() {
        return this.referenceName;
    }
    
    public void setReferenceName(String referenceName) {
        this.referenceName = referenceName;
    }
    public String getReferralOrganizationName() {
        return this.referralOrganizationName;
    }
    
    public void setReferralOrganizationName(String referralOrganizationName) {
        this.referralOrganizationName = referralOrganizationName;
    }
    public String getRefContactNo() {
        return this.refContactNo;
    }
    
    public void setRefContactNo(String refContactNo) {
        this.refContactNo = refContactNo;
    }
    public String getRefEmailAddress() {
        return this.refEmailAddress;
    }
    
    public void setRefEmailAddress(String refEmailAddress) {
        this.refEmailAddress = refEmailAddress;
    }
    public String getRefDesignation() {
        return this.refDesignation;
    }
    
    public void setRefDesignation(String refDesignation) {
        this.refDesignation = refDesignation;
    }
    public String getRefRelaltion() {
        return this.refRelaltion;
    }
    
    public void setRefRelaltion(String refRelaltion) {
        this.refRelaltion = refRelaltion;
    }




}


