package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RecieptDocuments generated by hbm2java
 */
public class RecieptDocuments  implements java.io.Serializable {


     private BigDecimal recieptid;
     private String filetype;
     private String pathname;
     private String status;

    public RecieptDocuments() {
    }

	
    public RecieptDocuments(BigDecimal recieptid) {
        this.recieptid = recieptid;
    }
    public RecieptDocuments(BigDecimal recieptid, String filetype, String pathname, String status) {
       this.recieptid = recieptid;
       this.filetype = filetype;
       this.pathname = pathname;
       this.status = status;
    }
   
    public BigDecimal getRecieptid() {
        return this.recieptid;
    }
    
    public void setRecieptid(BigDecimal recieptid) {
        this.recieptid = recieptid;
    }

    public String getFiletype() {
        return filetype;
    }

    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }



    public String getPathname() {
        return this.pathname;
    }
    
    public void setPathname(String pathname) {
        this.pathname = pathname;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


