package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TravelReimbursment generated by hbm2java
 */
public class Reimbursment  implements java.io.Serializable {


     private BigDecimal id;
     private String employeeid;
     private String reciept;
     private Date travelDate;
     private String travelFrom;
     private String travelTo;
     private String travelBy;
     private Double travelCost;
     private Double mealCost;
     private Double entertainmentCost;
     private Double totalamount;
     private String reason;
     private String requeststatus;
     private String tomail;
     private String recieptcopy;
     private String approvalauthoriyEmployeeid;
     private Date requestdate;
     private Date approvaldate;

    public Reimbursment() {
    }

	
    public Reimbursment(BigDecimal id) {
        this.id = id;
    }
    public Reimbursment(BigDecimal id, String employeeid, String reciept, Date travelDate, String travelFrom, String travelTo, String travelBy, Double travelCost, Double mealCost, Double entertainmentCost, Double totalamount, String reason, String requeststatus, String tomail, String recieptcopy, String approvalauthoriyEmployeeid, Date requestdate, Date approvaldate) {
       this.id = id;
       this.employeeid = employeeid;
       this.reciept = reciept;
       this.travelDate = travelDate;
       this.travelFrom = travelFrom;
       this.travelTo = travelTo;
       this.travelBy = travelBy;
       this.travelCost = travelCost;
       this.mealCost = mealCost;
       this.entertainmentCost = entertainmentCost;
       this.totalamount = totalamount;
       this.reason = reason;
       this.requeststatus = requeststatus;
       this.tomail = tomail;
       this.recieptcopy = recieptcopy;
       this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
       this.requestdate = requestdate;
       this.approvaldate = approvaldate;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    public String getReciept() {
        return this.reciept;
    }
    
    public void setReciept(String reciept) {
        this.reciept = reciept;
    }
    public Date getTravelDate() {
        return this.travelDate;
    }
    
    public void setTravelDate(Date travelDate) {
        this.travelDate = travelDate;
    }
    public String getTravelFrom() {
        return this.travelFrom;
    }
    
    public void setTravelFrom(String travelFrom) {
        this.travelFrom = travelFrom;
    }
    public String getTravelTo() {
        return this.travelTo;
    }
    
    public void setTravelTo(String travelTo) {
        this.travelTo = travelTo;
    }
    public String getTravelBy() {
        return this.travelBy;
    }
    
    public void setTravelBy(String travelBy) {
        this.travelBy = travelBy;
    }
    public Double getTravelCost() {
        return this.travelCost;
    }
    
    public void setTravelCost(Double travelCost) {
        this.travelCost = travelCost;
    }
    public Double getMealCost() {
        return this.mealCost;
    }
    
    public void setMealCost(Double mealCost) {
        this.mealCost = mealCost;
    }
    public Double getEntertainmentCost() {
        return this.entertainmentCost;
    }
    
    public void setEntertainmentCost(Double entertainmentCost) {
        this.entertainmentCost = entertainmentCost;
    }
    public Double getTotalamount() {
        return this.totalamount;
    }
    
    public void setTotalamount(Double totalamount) {
        this.totalamount = totalamount;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getRequeststatus() {
        return this.requeststatus;
    }
    
    public void setRequeststatus(String requeststatus) {
        this.requeststatus = requeststatus;
    }
    public String getTomail() {
        return this.tomail;
    }
    
    public void setTomail(String tomail) {
        this.tomail = tomail;
    }
    public String getRecieptcopy() {
        return this.recieptcopy;
    }
    
    public void setRecieptcopy(String recieptcopy) {
        this.recieptcopy = recieptcopy;
    }
    public String getApprovalauthoriyEmployeeid() {
        return this.approvalauthoriyEmployeeid;
    }
    
    public void setApprovalauthoriyEmployeeid(String approvalauthoriyEmployeeid) {
        this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
    }
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }




}


