package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RoleMaster generated by hbm2java
 */
public class RoleMaster  implements java.io.Serializable {


     private BigDecimal roleId;
     private String roleName;
     private String roleDescription;
     private BigDecimal rolePriority;
     private Set<DesignationMaster> designationMasters = new HashSet<DesignationMaster>(0);

    public RoleMaster() {
    }

	
    public RoleMaster(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public RoleMaster(BigDecimal roleId, String roleName, String roleDescription, BigDecimal rolePriority, Set<DesignationMaster> designationMasters) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.rolePriority = rolePriority;
       this.designationMasters = designationMasters;
    }
   
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    public BigDecimal getRolePriority() {
        return this.rolePriority;
    }
    
    public void setRolePriority(BigDecimal rolePriority) {
        this.rolePriority = rolePriority;
    }
    public Set<DesignationMaster> getDesignationMasters() {
        return this.designationMasters;
    }
    
    public void setDesignationMasters(Set<DesignationMaster> designationMasters) {
        this.designationMasters = designationMasters;
    }




}


