package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StateMaster generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private BigDecimal stateId;
     private CountryMaster countryMaster;
     private String stateName;
     private Date creationDate;
     private Date modificationDate;
     private String createdBy;
     private String modifiedBy;
     private String status;
     private Set<City> cityMasters = new HashSet<City>(0);

    public State() {
    }

	
    public State(BigDecimal stateId) {
        this.stateId = stateId;
    }
    public State(BigDecimal stateId, CountryMaster countryMaster, String stateName, Date creationDate, Date modificationDate, String createdBy, String modifiedBy, String status, Set<City> cityMasters) {
       this.stateId = stateId;
       this.countryMaster = countryMaster;
       this.stateName = stateName;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.status = status;
       this.cityMasters = cityMasters;
    }
   
    public BigDecimal getStateId() {
        return this.stateId;
    }
    
    public void setStateId(BigDecimal stateId) {
        this.stateId = stateId;
    }
    public CountryMaster getCountryMaster() {
        return this.countryMaster;
    }
    
    public void setCountryMaster(CountryMaster countryMaster) {
        this.countryMaster = countryMaster;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<City> getCityMasters() {
        return this.cityMasters;
    }
    
    public void setCityMasters(Set<City> cityMasters) {
        this.cityMasters = cityMasters;
    }




}


