package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TaskMaster generated by hbm2java
 */
public class TaskMaster  implements java.io.Serializable {


     private BigDecimal taskId;
     private String taskName;
     private String taskDescription;
     private String status;

    public TaskMaster() {
    }

	
    public TaskMaster(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public TaskMaster(BigDecimal taskId, String taskName, String taskDescription, String status) {
       this.taskId = taskId;
       this.taskName = taskName;
       this.taskDescription = taskDescription;
       this.status = status;
    }
   
    public BigDecimal getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    public String getTaskDescription() {
        return this.taskDescription;
    }
    
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


