package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TimesheetDetail generated by java
 */
public class TimesheetDetail  implements java.io.Serializable {


     private BigDecimal timesheetdetailid;
     private BigDecimal timesheetheaderid;
     private BigDecimal projectid;
     private String timeslot;
     private String description;
     private String empid;
     private Date timesheetdate;
     private String overtimestatus;
     private String approvestatus;
     private String reason;

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getApprovestatus() {
        return approvestatus;
    }

    public void setApprovestatus(String approvestatus) {
        this.approvestatus = approvestatus;
    }

    public String getOvertimestatus() {
        return overtimestatus;
    }

    public void setOvertimestatus(String overtimestatus) {
        this.overtimestatus = overtimestatus;
    }

    public TimesheetDetail(BigDecimal timesheetdetailid, BigDecimal timesheetheaderid, BigDecimal projectid, String timeslot, String description, String empid, Date timesheetdate, String overtimestatus, String approvestatus) {
        this.timesheetdetailid = timesheetdetailid;
        this.timesheetheaderid = timesheetheaderid;
        this.projectid = projectid;
        this.timeslot = timeslot;
        this.description = description;
        this.empid = empid;
        this.timesheetdate = timesheetdate;
        this.overtimestatus = overtimestatus;
        this.approvestatus = approvestatus;
    }

    public TimesheetDetail(BigDecimal timesheetdetailid, BigDecimal timesheetheaderid, BigDecimal projectid, String timeslot, String description, String empid, Date timesheetdate) {
        this.timesheetdetailid = timesheetdetailid;
        this.timesheetheaderid = timesheetheaderid;
        this.projectid = projectid;
        this.timeslot = timeslot;
        this.description = description;
        this.empid = empid;
        this.timesheetdate = timesheetdate;
    }


    public String getEmpid() {
        return empid;
    }

    public void setEmpid(String empid) {
        this.empid = empid;
    }

    public Date getTimesheetdate() {
        return timesheetdate;
    }

    public void setTimesheetdate(Date timesheetdate) {
        this.timesheetdate = timesheetdate;
    }



    public TimesheetDetail() {
    }

	
    public TimesheetDetail(BigDecimal timesheetdetailid) {
        this.timesheetdetailid = timesheetdetailid;
    }
    public TimesheetDetail(BigDecimal timesheetdetailid, BigDecimal timesheetheaderid, BigDecimal projectid, String timeslot, String description) {
       this.timesheetdetailid = timesheetdetailid;
       this.timesheetheaderid = timesheetheaderid;
       this.projectid = projectid;
       this.timeslot = timeslot;
       this.description = description;
    }
   
    public BigDecimal getTimesheetdetailid() {
        return this.timesheetdetailid;
    }
    
    public void setTimesheetdetailid(BigDecimal timesheetdetailid) {
        this.timesheetdetailid = timesheetdetailid;
    }
    public BigDecimal getTimesheetheaderid() {
        return this.timesheetheaderid;
    }
    
    public void setTimesheetheaderid(BigDecimal timesheetheaderid) {
        this.timesheetheaderid = timesheetheaderid;
    }
    public BigDecimal getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(BigDecimal projectid) {
        this.projectid = projectid;
    }
    public String getTimeslot() {
        return this.timeslot;
    }
    
    public void setTimeslot(String timeslot) {
        this.timeslot = timeslot;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


