package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TimesheetHeader generated by hbm2java
 */
public class TimesheetHeader  implements java.io.Serializable {


     private BigDecimal headerid;
     private Date workingdate;
     private Date creationdate;
     private BigDecimal normalworkduration;
     private BigDecimal overtimeduration;
     private BigDecimal deptid;
     private BigDecimal empid;
     private BigDecimal companyid;
     private BigDecimal overtimeprojectid;
     private String creatorid;
     private String starttime;
     private String overtimeslot;
     private String otdescription;

    public TimesheetHeader() {
    }

	
    public TimesheetHeader(BigDecimal headerid) {
        this.headerid = headerid;
    }

    public TimesheetHeader(BigDecimal headerid, Date workingdate, Date creationdate, BigDecimal normalworkduration, BigDecimal overtimeduration, BigDecimal deptid, BigDecimal empid, BigDecimal companyid, BigDecimal overtimeprojectid, String creatorid, String starttime, String overtimeslot, String otdescription) {
        this.headerid = headerid;
        this.workingdate = workingdate;
        this.creationdate = creationdate;
        this.normalworkduration = normalworkduration;
        this.overtimeduration = overtimeduration;
        this.deptid = deptid;
        this.empid = empid;
        this.companyid = companyid;
        this.overtimeprojectid = overtimeprojectid;
        this.creatorid = creatorid;
        this.starttime = starttime;
        this.overtimeslot = overtimeslot;
        this.otdescription = otdescription;
    }
   
    public BigDecimal getHeaderid() {
        return this.headerid;
    }
    
    public void setHeaderid(BigDecimal headerid) {
        this.headerid = headerid;
    }
    public Date getWorkingdate() {
        return this.workingdate;
    }
    
    public void setWorkingdate(Date workingdate) {
        this.workingdate = workingdate;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public BigDecimal getNormalworkduration() {
        return this.normalworkduration;
    }
    
    public void setNormalworkduration(BigDecimal normalworkduration) {
        this.normalworkduration = normalworkduration;
    }
    public BigDecimal getOvertimeduration() {
        return this.overtimeduration;
    }
    
    public void setOvertimeduration(BigDecimal overtimeduration) {
        this.overtimeduration = overtimeduration;
    }
    public BigDecimal getDeptid() {
        return this.deptid;
    }
    
    public void setDeptid(BigDecimal deptid) {
        this.deptid = deptid;
    }
    public BigDecimal getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(BigDecimal empid) {
        this.empid = empid;
    }
    public BigDecimal getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }
    public BigDecimal getOvertimeprojectid() {
        return this.overtimeprojectid;
    }
    
    public void setOvertimeprojectid(BigDecimal overtimeprojectid) {
        this.overtimeprojectid = overtimeprojectid;
    }

    public String getCreatorid() {
        return creatorid;
    }

    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid;
    }
 
    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }
    public String getOvertimeslot() {
        return this.overtimeslot;
    }
    
    public void setOvertimeslot(String overtimeslot) {
        this.overtimeslot = overtimeslot;
    }
    public String getOtdescription() {
        return this.otdescription;
    }
    
    public void setOtdescription(String otdescription) {
        this.otdescription = otdescription;
    }




}


