package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TrainingMaster generated by hbm2java
 */
public class TrainingMaster  implements java.io.Serializable {


     private BigDecimal trainingId;
     private String trainingType;
     private String trainingName;
     private String trainer;
     private BigDecimal consultacyId;
     private String status;
     private BigDecimal departmentId;
     private BigDecimal skillId;
     private BigDecimal typeId;
     private Set<TrainingTrainingType> trainingTrainingTypes = new HashSet<TrainingTrainingType>(0);

    public TrainingMaster() {
    }

	
    public TrainingMaster(BigDecimal trainingId) {
        this.trainingId = trainingId;
    }
    public TrainingMaster(BigDecimal trainingId, String trainingType, String trainingName, String trainer, BigDecimal consultacyId, String status, BigDecimal departmentId, BigDecimal skillId, BigDecimal typeId, Set<TrainingTrainingType> trainingTrainingTypes) {
       this.trainingId = trainingId;
       this.trainingType = trainingType;
       this.trainingName = trainingName;
       this.trainer = trainer;
       this.consultacyId = consultacyId;
       this.status = status;
       this.departmentId = departmentId;
       this.skillId = skillId;
       this.typeId = typeId;
       this.trainingTrainingTypes = trainingTrainingTypes;
    }
   
    public BigDecimal getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(BigDecimal trainingId) {
        this.trainingId = trainingId;
    }
    public String getTrainingType() {
        return this.trainingType;
    }
    
    public void setTrainingType(String trainingType) {
        this.trainingType = trainingType;
    }
    public String getTrainingName() {
        return this.trainingName;
    }
    
    public void setTrainingName(String trainingName) {
        this.trainingName = trainingName;
    }
    public String getTrainer() {
        return this.trainer;
    }
    
    public void setTrainer(String trainer) {
        this.trainer = trainer;
    }
    public BigDecimal getConsultacyId() {
        return this.consultacyId;
    }
    
    public void setConsultacyId(BigDecimal consultacyId) {
        this.consultacyId = consultacyId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(BigDecimal departmentId) {
        this.departmentId = departmentId;
    }
    public BigDecimal getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(BigDecimal skillId) {
        this.skillId = skillId;
    }
    public BigDecimal getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(BigDecimal typeId) {
        this.typeId = typeId;
    }
    public Set<TrainingTrainingType> getTrainingTrainingTypes() {
        return this.trainingTrainingTypes;
    }
    
    public void setTrainingTrainingTypes(Set<TrainingTrainingType> trainingTrainingTypes) {
        this.trainingTrainingTypes = trainingTrainingTypes;
    }




}


