package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TrainingRequestMaster generated by hbm2java
 */
public class TrainingRequestMaster  implements java.io.Serializable {


     private BigDecimal requestId;
     private BigDecimal trainingId;
     private Date fromDate;
     private Date toDate;
     private String status;
     private BigDecimal employeeApplyId;
     private BigDecimal employeeApproveId;
     private TrainingMaster training;

    public TrainingMaster getTraining() {
        return training;
    }

    public void setTraining(TrainingMaster training) {
        this.training = training;
    }


    public TrainingRequestMaster() {
    }

	
    public TrainingRequestMaster(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public TrainingRequestMaster(BigDecimal requestId, BigDecimal trainingId, Date fromDate, Date toDate, String status, BigDecimal employeeApplyId, BigDecimal employeeApproveId) {
       this.requestId = requestId;
       this.trainingId = trainingId;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.status = status;
       this.employeeApplyId = employeeApplyId;
       this.employeeApproveId = employeeApproveId;
    }
   
    public BigDecimal getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public BigDecimal getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(BigDecimal trainingId) {
        this.trainingId = trainingId;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getEmployeeApplyId() {
        return this.employeeApplyId;
    }
    
    public void setEmployeeApplyId(BigDecimal employeeApplyId) {
        this.employeeApplyId = employeeApplyId;
    }
    public BigDecimal getEmployeeApproveId() {
        return this.employeeApproveId;
    }
    
    public void setEmployeeApproveId(BigDecimal employeeApproveId) {
        this.employeeApproveId = employeeApproveId;
    }




}


