package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TrainingType generated by hbm2java
 */
public class TrainingType  implements java.io.Serializable {


     private BigDecimal trainingTypeId;
     private String typeName;
     private String status;

    public TrainingType() {
    }

	
    public TrainingType(BigDecimal trainingTypeId) {
        this.trainingTypeId = trainingTypeId;
    }
    public TrainingType(BigDecimal trainingTypeId, String typeName, String status) {
       this.trainingTypeId = trainingTypeId;
       this.typeName = typeName;
       this.status = status;
    }
   
    public BigDecimal getTrainingTypeId() {
        return this.trainingTypeId;
    }
    
    public void setTrainingTypeId(BigDecimal trainingTypeId) {
        this.trainingTypeId = trainingTypeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


