package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TrainingTrainingType generated by hbm2java
 */
public class TrainingTrainingType  implements java.io.Serializable {


     private BigDecimal trainingId;
     private TrainingMaster trainingMaster;
     private BigDecimal trainingTypeId;

    public TrainingTrainingType() {
    }

    public TrainingTrainingType(BigDecimal trainingId, TrainingMaster trainingMaster, BigDecimal trainingTypeId) {
       this.trainingId = trainingId;
       this.trainingMaster = trainingMaster;
       this.trainingTypeId = trainingTypeId;
    }
   
    public BigDecimal getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(BigDecimal trainingId) {
        this.trainingId = trainingId;
    }
    public TrainingMaster getTrainingMaster() {
        return this.trainingMaster;
    }
    
    public void setTrainingMaster(TrainingMaster trainingMaster) {
        this.trainingMaster = trainingMaster;
    }
    public BigDecimal getTrainingTypeId() {
        return this.trainingTypeId;
    }
    
    public void setTrainingTypeId(BigDecimal trainingTypeId) {
        this.trainingTypeId = trainingTypeId;
    }




}


