package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TransportMaster generated by hbm2java
 */
public class TransportMaster  implements java.io.Serializable {


     private BigDecimal transportid;
     private String transportname;
     private String status;

    public TransportMaster() {
    }

	
    public TransportMaster(BigDecimal transportid) {
        this.transportid = transportid;
    }
    public TransportMaster(BigDecimal transportid, String transportname, String status) {
       this.transportid = transportid;
       this.transportname = transportname;
       this.status = status;
    }
   
    public BigDecimal getTransportid() {
        return this.transportid;
    }
    
    public void setTransportid(BigDecimal transportid) {
        this.transportid = transportid;
    }
    public String getTransportname() {
        return this.transportname;
    }
    
    public void setTransportname(String transportname) {
        this.transportname = transportname;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


