package com.pojo;
// Generated Nov 11, 2010 2:05:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transport generated by hbm2java
 */
public class Transport  implements java.io.Serializable {


     private BigDecimal requestId;
     private String employeeid;
     private String transportname;
     private String transportFrom;
     private String transportTo;
     private Date transportDate;
     private String departuretime;
     private String reason;
     private String requeststatus;
     private String tomail;
     private String approvalauthoriyEmployeeid;
     private Date requestdate;
     private Date approvaldate;

    public Transport() {
    }

	
    public Transport(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public Transport(BigDecimal requestId, String employeeid, String transportname, String transportFrom, String transportTo, Date transportDate, String departuretime, String reason, String requeststatus, String tomail, String approvalauthoriyEmployeeid, Date requestdate, Date approvaldate) {
       this.requestId = requestId;
       this.employeeid = employeeid;
       this.transportname = transportname;
       this.transportFrom = transportFrom;
       this.transportTo = transportTo;
       this.transportDate = transportDate;
       this.departuretime = departuretime;
       this.reason = reason;
       this.requeststatus = requeststatus;
       this.tomail = tomail;
       this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
       this.requestdate = requestdate;
       this.approvaldate = approvaldate;
    }
   
    public BigDecimal getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(BigDecimal requestId) {
        this.requestId = requestId;
    }
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    public String getTransportname() {
        return this.transportname;
    }
    
    public void setTransportname(String transportname) {
        this.transportname = transportname;
    }
    public String getTransportFrom() {
        return this.transportFrom;
    }
    
    public void setTransportFrom(String transportFrom) {
        this.transportFrom = transportFrom;
    }
    public String getTransportTo() {
        return this.transportTo;
    }
    
    public void setTransportTo(String transportTo) {
        this.transportTo = transportTo;
    }
    public Date getTransportDate() {
        return this.transportDate;
    }
    
    public void setTransportDate(Date transportDate) {
        this.transportDate = transportDate;
    }
    public String getDeparturetime() {
        return this.departuretime;
    }
    
    public void setDeparturetime(String departuretime) {
        this.departuretime = departuretime;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getRequeststatus() {
        return this.requeststatus;
    }
    
    public void setRequeststatus(String requeststatus) {
        this.requeststatus = requeststatus;
    }
    public String getTomail() {
        return this.tomail;
    }
    
    public void setTomail(String tomail) {
        this.tomail = tomail;
    }
    public String getApprovalauthoriyEmployeeid() {
        return this.approvalauthoriyEmployeeid;
    }
    
    public void setApprovalauthoriyEmployeeid(String approvalauthoriyEmployeeid) {
        this.approvalauthoriyEmployeeid = approvalauthoriyEmployeeid;
    }
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }




}


